### ISSUE TITLE
Correção Exercício `0.5.1`

### ISSUE THREAD

**Issue by mathiasgheno** [Dioguinxz/TI23-DW1#2]
# Correção Exercício `0.5.1`

> Considere o wireframe abaixo como um guia visual para um sistema web que faz listagem de tarefas considerando três status: Pendentes, Concluídas e Excluídas.  [Referência visual](https://i.imgur.com/AsfPVcN.jpg). 

Tudo ok.

**Nota:** 10

## Comentários

https://github.com/Dioguinxz/TI23-DW1/blob/5b9cc6ca4181e17547511beea99fbc3f16f5d32f/Ex%200.5.1/styles.css#L45-L78

Toda propriedade que é repetida várias vazes podem ser centralizada em outra classe. Dessa forma, se você tiver q modificar o valor dessa propriedade você só precisa mudar em um local. 

```css
.animacao {
    transition: all 0.2s ease-in-out;
}

.concluidas {
    background-color: #0ca789;
}
```

No HTML bastaria fazer uso das duas classes. 

```html
<nav>
    <button class="animacao pendentes"><a href="index.html">Pendentes</a></button>
</nav>
```

Você também poderia fazer o uso das variaveis css para essa centralizacao. 

```css
:root {
    --animacao: all 0.2s ease-in-out;
}

.concluidas {
    background-color: #0ca789;
    transition: var(--animacao);
}
```

[^1]: [Caminhos: entenda as diferenças entre absolutos e relativos](https://www.alura.com.br/artigos/caminhos-entenda-diferencas-entre-absolutos-relativos?gclid=CjwKCAjw9J2iBhBPEiwAErwpeZOH615fG9QWBpSN2UuIKVbpf6WWD9sknST-4DwVDHzcCBBuMOYuzhoCbNsQAvD_BwE)
[^2]: [CSS Selectors ─ Element Element Selector](https://www.w3schools.com/cssref/sel_element_element.php)
[^3]: [CSS Variables ─ An Introduction](https://youtu.be/PHO6TBq_auI)
[^4]: [HTML Lists](https://www.w3schools.com/html/html_lists.asp)
